# Generated by Django 5.1.1 on 2024-10-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_user_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="postimage",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
