# Generated by Django 5.1.1 on 2024-10-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_room_postimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="postimage",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
