# Generated by Django 5.1.1 on 2024-10-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="postimage",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
