# Generated by Django 5.1.1 on 2024-10-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_roomfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="postimage",
        ),
    ]
