# Generated by Django 5.1.1 on 2024-10-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_remove_room_postimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="full_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatar.svg", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="background",
            field=models.ImageField(
                blank=True,
                default="background_for_profile_info.jpg",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="occupation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
