# Generated by Django 5.1.1 on 2024-10-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="background",
            field=models.ImageField(
                blank=True,
                default="default/background_for_profile_info.jpg",
                null=True,
                upload_to="",
            ),
        ),
    ]
