# Generated by Django 5.1.1 on 2024-10-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_user_background"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="default/avatar.svg", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="background",
            field=models.ImageField(
                default="default/background_for_profile_info.jpg",
                null=True,
                upload_to="",
            ),
        ),
    ]
