# Generated by Django 5.1.1 on 2024-10-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_alter_user_avatar_alter_user_background"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="background",
            field=models.ImageField(
                default="default/background.jpg", upload_to="images/"
            ),
        ),
    ]
