# Generated by Django 5.1.1 on 2024-10-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="background",
            field=models.ImageField(default="background.jpg", null=True, upload_to=""),
        ),
    ]
