# Generated by Django 5.1.1 on 2024-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_alter_user_background"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
