# Generated by Django 5.1.1 on 2024-10-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_alter_topic_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="name",
        ),
    ]
