# Generated by Django 5.1.1 on 2024-10-10 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0028_alter_message_recipient_alter_message_sender"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("user", "connection")},
        ),
    ]
