# Generated by Django 3.2.7 on 2025-09-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20250909_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('employer', 'Employer')], max_length=20, null=True),
        ),
    ]
