# Generated by Django 3.2.7 on 2025-09-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
