# Generated by Django 3.2.7 on 2025-09-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_usergooglecredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_shown',
            field=models.BooleanField(default=False),
        ),
    ]
