# Generated by Django 3.2.7 on 2025-09-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_user_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyswipequota',
            name='limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
